export interface LedgerDetail {
  _id : string;
  OrderId : string;
  OrderNumber :string;
  BillingName : string;
  AddressLine1 : string;
  AddressLine2: string;
  AddressLine3: string;
  City: string;
  State: string;
  Pincode: string;
  CDProfile1: string;
  CDName1: string;
  CDMobile1: string;
  CDEmail1: string;
  CDProfile2: string;
  CDName2: string;
  CDMobile2: string;
  CDEmail2: string;
  CDProfile3: string;
  CDName3: string;
  CDMobile3: string;
  CDEmail3: string;
  CompanyName: string;
  Website: string;
  AddressLine1Con: string;
  AddressLine2Con: string;
  AddressLine3Con: string;
  CityCon: string;
  StateCon: string;
  PincodeCon: string;
  ConProfile1: string;
  ConName1: string;
  ConPhone1: string;
  ConEmail1: string;
  ConProfile2: string;
  ConName2: string;
  ConPhone2: string;
  ConEmail2:  string;
  ProPlus:  string;
  ProPlusCost: string;

  }
